---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "merge-pr"
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^/deploy"
spec:
  params:
    - name: message
      value: "Sample Message"
  pipelineSpec:
    params:
    - description: Message
      name: message
      type: string
    tasks:
    - name: echo-sample-message
      params:
        - name: message
          value: $(params.message)
      taskSpec:
        steps:
          - name: echo-sample-message
            image: images.paas.redhat.com/avsingh/dev-tools
            script: |
              echo -n $message